=== rune-goblin/foundry-mothership/content/data/schema/contractors.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://runegoblin.dev/mothership/contractors.schema.json",
  "title": "Contractors",
  "type": "object",
  "required": ["id", "name", "die", "results"],
  "properties": {
    "id": { "$ref": "common.schema.json#/$defs/id" },
    "name": { "type": "string", "minLength": 1 },
    "die": { "const": "1d100" },
    "results": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["id", "range", "occupation", "salary", "combat",
                     "instinct", "maxWounds", "motivation", "source"],
        "properties": {
          "id": { "$ref": "common.schema.json#/$defs/id" },
          "range": { "$ref": "common.schema.json#/$defs/rollRange" },
          "occupation": { "type": "string", "minLength": 1 },
          "salary": { "$ref": "common.schema.json#/$defs/cost" },
          "combat": { "type": "integer", "minimum": 0, "maximum": 100 },
          "instinct": { "type": "integer", "minimum": 0, "maximum": 100 },
          "maxWounds": { "type": "integer", "minimum": 1 },
          "motivation": { "type": "string", "minLength": 1 },
          "source": { "$ref": "common.schema.json#/$defs/source" }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== rune-goblin/foundry-mothership/content/data/contractors.json
{
  "id": "contractors",
  "name": "Contractors",
  "die": "1d100",
  "results": [
    {
      "id": "archaeologist",
      "range": [
        0,
        0
      ],
      "occupation": "Archaeologist",
      "salary": {
        "raw": "6kcr",
        "value": 6000,
        "each": false
      },
      "combat": 20,
      "instinct": 15,
      "maxWounds": 1,
      "motivation": "Secretly investigating a Corporate cover-up.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "asteroid-miner",
      "range": [
        1,
        9
      ],
      "occupation": "Asteroid Miner",
      "salary": {
        "raw": "2kcr",
        "value": 2000,
        "each": false
      },
      "combat": 25,
      "instinct": 25,
      "maxWounds": 2,
      "motivation": "Sending money back home to family.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "android",
      "range": [
        10,
        19
      ],
      "occupation": "Android",
      "salary": {
        "raw": "6kcr",
        "value": 6000,
        "each": false
      },
      "combat": 20,
      "instinct": 35,
      "maxWounds": 2,
      "motivation": "Badly needs to pay off a loan shark.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "bodyguard",
      "range": [
        20,
        24
      ],
      "occupation": "Bodyguard",
      "salary": {
        "raw": "2kcr",
        "value": 2000,
        "each": false
      },
      "combat": 30,
      "instinct": 25,
      "maxWounds": 2,
      "motivation": "Can't stop in one place for too long, gets restless.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "captain",
      "range": [
        25,
        29
      ],
      "occupation": "Captain",
      "salary": {
        "raw": "10kcr",
        "value": 10000,
        "each": false
      },
      "combat": 30,
      "instinct": 40,
      "maxWounds": 3,
      "motivation": "Hears a call from an entity they can't explain.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "chaplain",
      "range": [
        30,
        34
      ],
      "occupation": "Chaplain",
      "salary": {
        "raw": "750cr",
        "value": 750,
        "each": false
      },
      "combat": 10,
      "instinct": 20,
      "maxWounds": 2,
      "motivation": "Using you/your ship to smuggle contraband.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "corporate-fixer",
      "range": [
        35,
        39
      ],
      "occupation": "Corporate Fixer",
      "salary": {
        "raw": "24kcr",
        "value": 24000,
        "each": false
      },
      "combat": 15,
      "instinct": 30,
      "maxWounds": 1,
      "motivation": "Revenge.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "doctor",
      "range": [
        40,
        44
      ],
      "occupation": "Doctor",
      "salary": {
        "raw": "8kcr",
        "value": 8000,
        "each": false
      },
      "combat": 15,
      "instinct": 25,
      "maxWounds": 1,
      "motivation": "Secretly a con artist with no other expertise.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "engineer",
      "range": [
        45,
        49
      ],
      "occupation": "Engineer",
      "salary": {
        "raw": "7kcr",
        "value": 7000,
        "each": false
      },
      "combat": 20,
      "instinct": 25,
      "maxWounds": 2,
      "motivation": "Paying a loved one's medical bills.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "hacker",
      "range": [
        50,
        54
      ],
      "occupation": "Hacker",
      "salary": {
        "raw": "8kcr",
        "value": 8000,
        "each": false
      },
      "combat": 15,
      "instinct": 30,
      "maxWounds": 1,
      "motivation": "Secretly a spy for a rival corporation.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "marine-grunt",
      "range": [
        55,
        59
      ],
      "occupation": "Marine (Grunt)",
      "salary": {
        "raw": "1.5kcr",
        "value": 1500,
        "each": false
      },
      "combat": 30,
      "instinct": 25,
      "maxWounds": 2,
      "motivation": "Need to pay off jumped bail or a court fine.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "marine-officer",
      "range": [
        60,
        64
      ],
      "occupation": "Marine (Officer)",
      "salary": {
        "raw": "3.5kcr",
        "value": 3500,
        "each": false
      },
      "combat": 35,
      "instinct": 35,
      "maxWounds": 3,
      "motivation": "Undercover secret police investigating your crew.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "pilot",
      "range": [
        65,
        69
      ],
      "occupation": "Pilot",
      "salary": {
        "raw": "3kcr",
        "value": 3000,
        "each": false
      },
      "combat": 15,
      "instinct": 25,
      "maxWounds": 1,
      "motivation": "In huge debt to a powerful crime syndicate.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "pioneer",
      "range": [
        70,
        74
      ],
      "occupation": "Pioneer",
      "salary": {
        "raw": "1.5kcr",
        "value": 1500,
        "each": false
      },
      "combat": 25,
      "instinct": 25,
      "maxWounds": 1,
      "motivation": "Took the money and ran out on their last job.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "scientist",
      "range": [
        75,
        79
      ],
      "occupation": "Scientist",
      "salary": {
        "raw": "4kcr",
        "value": 4000,
        "each": false
      },
      "combat": 15,
      "instinct": 10,
      "maxWounds": 1,
      "motivation": "Family member held hostage, needs ransom.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "survival-guide",
      "range": [
        80,
        84
      ],
      "occupation": "Survival Guide",
      "salary": {
        "raw": "3kcr",
        "value": 3000,
        "each": false
      },
      "combat": 30,
      "instinct": 35,
      "maxWounds": 2,
      "motivation": "Secretly a bounty hunter looking for your crew.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "surgeon",
      "range": [
        85,
        89
      ],
      "occupation": "Surgeon",
      "salary": {
        "raw": "12kcr",
        "value": 12000,
        "each": false
      },
      "combat": 15,
      "instinct": 20,
      "maxWounds": 1,
      "motivation": "Seeking an honorable and glorious death.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "teamster",
      "range": [
        90,
        94
      ],
      "occupation": "Teamster",
      "salary": {
        "raw": "2kcr",
        "value": 2000,
        "each": false
      },
      "combat": 25,
      "instinct": 25,
      "maxWounds": 1,
      "motivation": "Unknowingly contagious with a deadly disease.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
      "id": "therapist",
      "range": [
        95,
        98
      ],
      "occupation": "Therapist",
      "salary": {
        "raw": "3kcr",
        "value": 3000,
        "each": false
      },
      "combat": 10,
      "instinct": 20,
      "maxWounds": 1,
      "motivation": "Escaped from a corporate research facility.",
      "source": {
        "book": "Player's Survival Guide",
        "system": "mothership-1e",
        "version": "1.2",
        "page": 41,
        "section": "40.1"
      }
    },
    {
